### ISSUE TITLE
API key for Open Weather Map is in repo

### ISSUE THREAD

**Issue by jarofgreen** [maaarghk/SteamieBot#3]
You probably didn't want to check that in :-)

**Comment by timlardner** [comment]
Balls. Thanks for letting us know.

**Comment by maaarghk** [comment]
@jarofgreen fixed. cheers for that. I'll let @timlardner deal with getting a new key and @incompetentfox with invalidating the old one :)

**Comment by jarofgreen** [comment]
No worries. (BTW seeing as your all Glasgow techies, let me cheekily plug https://opentechcalendar.co.uk/ :-p )

**Comment by maaarghk** [comment]
yeah i grab the ica from time to time, as well as being subscribed to https://groups.google.com/forum/#!forum/techmeetup incase any interesting jobs show up without having to move to edinburgh haha.

**Comment by timlardner** [comment]
New API key acquired and tested. Just need @incompetentfox to log in to his account and invalidate the old key.
