### ISSUE TITLE
Use forecast.io for weather

### ISSUE THREAD

**Issue by maaarghk** [maaarghk/SteamieBot#8]
forecast.io looks like a better option for weather, it gives you a little sentence describing the entire day's weather 

check it out: http://forecast.io/#/f/55.8679,-4.2600

**Comment by timlardner** [comment]
I've written stuff using forecast.io's API before. Should be easy enough to integrate.

**Comment by timlardner** [comment]
Updated Steamie with the new API. If a weather warning exists, it'll post that. Otherwise it'll post the daily summary and the temperature range.

See /r/steamiebottest for an example of each case - we've got a weather warning at the moment.

**Comment by maaarghk** [comment]
nice, I kind of think if there's a weather warning it should also display the normal weather details because the warning doesn't actually tell you what it's like where you are.

I've updated the live post with the new format cause it's awesome, cheers man.

**Comment by timlardner** [comment]
Cool, it now will display the normal weather as well as the warning. Changes pulled to my server and tested.
